package com.message.mesh.security;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("JwtUtil")
class JwtUtilTest {

    private static final String SECRET = "test-only-secret-key-that-is-long-enough-to-be-valid-32b+";

    private JwtUtil jwtUtil;

    @BeforeEach
    void setUp() {
        jwtUtil = new JwtUtil(SECRET, 86_400_000L);
    }

    @Test
    @DisplayName("generateToken produces a token whose subject is the username")
    void generateTokenCarriesUsername() {
        String token = jwtUtil.generateToken("alice");

        assertThat(jwtUtil.isValid(token)).isTrue();
        assertThat(jwtUtil.getUsername(token)).isEqualTo("alice");
        assertThat(jwtUtil.getTokenVersion(token)).isZero();
    }

    @Test
    @DisplayName("generateToken embeds the token version claim")
    void generateTokenCarriesTokenVersion() {
        String token = jwtUtil.generateToken("alice", 7);

        assertThat(jwtUtil.getTokenVersion(token)).isEqualTo(7);
    }

    @Test
    @DisplayName("isValid returns false for a malformed token")
    void isValidRejectsMalformedToken() {
        assertThat(jwtUtil.isValid("not-a-jwt")).isFalse();
    }

    @Test
    @DisplayName("isValid returns false for a token signed with a different key")
    void isValidRejectsForeignSignature() {
        JwtUtil other = new JwtUtil("another-completely-different-secret-key-that-is-long-32b+", 86_400_000L);
        String foreignToken = other.generateToken("alice");

        assertThat(jwtUtil.isValid(foreignToken)).isFalse();
    }

    @Test
    @DisplayName("isValid returns false for an expired token")
    void isValidRejectsExpiredToken() {
        JwtUtil shortLived = new JwtUtil(SECRET, -1_000L);
        String expired = shortLived.generateToken("alice");

        assertThat(jwtUtil.isValid(expired)).isFalse();
    }

    @Test
    @DisplayName("getTokenVersion defaults to zero when the claim is absent")
    void getTokenVersionDefaultsToZero() {
        // A token generated by the single-arg overload still sets tv=0.
        String token = jwtUtil.generateToken("alice");
        assertThat(jwtUtil.getTokenVersion(token)).isZero();
    }
}
